#!/usr/bin/env bash
# generate-stats.sh - Aggregate stats across ALL features
# Output: Markdown stats report

set -euo pipefail

RELENTLESS_DIR="${1:-relentless}"
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

source "$SCRIPT_DIR/common.sh"

FEATURES_DIR="$RELENTLESS_DIR/features"

if [[ ! -d "$FEATURES_DIR" ]]; then
  echo "# Relentless Stats"
  echo ""
  echo "No features found in $FEATURES_DIR"
  exit 0
fi

# Check if jq is available
if ! command -v jq >/dev/null 2>&1; then
  echo "# Relentless Stats"
  echo ""
  echo "**Note:** jq not available - install for detailed stats"
  exit 0
fi

# Find all prd.json files
PRD_FILES=$(find "$FEATURES_DIR" -name "prd.json" -type f 2>/dev/null)

if [[ -z "$PRD_FILES" ]]; then
  echo "# Relentless Stats"
  echo ""
  echo "No prd.json files found"
  exit 0
fi

# Aggregate stats using jq - handle null values robustly
STATS=$(echo "$PRD_FILES" | xargs cat 2>/dev/null | jq -s '
{
  totalFeatures: length,
  totalStories: ([.[].userStories | length] | add // 0),
  completedStories: ([.[].userStories | map(select(.passes == true)) | length] | add // 0),
  skippedStories: ([.[].userStories | map(select(.skipped == true)) | length] | add // 0),
  totalEstimatedCost: ([.[].userStories[].routing.estimatedCost? // 0] | add // 0),
  totalActualCost: ([.[].userStories[].execution.actualCost? // 0] | add // 0),
  totalInputTokens: ([.[].userStories[].execution.inputTokens? // 0] | add // 0),
  totalOutputTokens: ([.[].userStories[].execution.outputTokens? // 0] | add // 0),
  escalations: ([.[].userStories | map(select(.execution.attempts? > 1)) | length] | add // 0),
  complexityBreakdown: {
    simple: ([.[].userStories | map(select(.routing.complexity? == "simple")) | length] | add // 0),
    medium: ([.[].userStories | map(select(.routing.complexity? == "medium")) | length] | add // 0),
    complex: ([.[].userStories | map(select(.routing.complexity? == "complex")) | length] | add // 0),
    expert: ([.[].userStories | map(select(.routing.complexity? == "expert")) | length] | add // 0)
  },
  modelUsage: []
}
' 2>/dev/null)

# Generate markdown report
TODAY=$(date +"%Y-%m-%d")

cat <<EOF
# Relentless Stats

**Last Updated**: $TODAY

## Summary

$(echo "$STATS" | jq -r '
"| Metric | Value |
|--------|-------|
| Total Features | \(.totalFeatures // 0) |
| Total Stories | \(.totalStories // 0) |
| Completed Stories | \(.completedStories // 0) |
| Skipped Stories | \(.skippedStories // 0) |
| Completion Rate | \(((.completedStories // 0) / ((.totalStories // 1) | if . == 0 then 1 else . end) * 100) | floor)% |"
')

## Cost Summary

$(echo "$STATS" | jq -r '
"| Metric | Value |
|--------|-------|
| Total Estimated Cost | $\(.totalEstimatedCost // 0 | . * 100 | floor / 100) |
| Total Actual Cost | $\(.totalActualCost // 0 | . * 100 | floor / 100) |
| Cost Accuracy | \(if (.totalEstimatedCost // 0) > 0 then (((.totalActualCost // 0) / .totalEstimatedCost * 100) | floor) else "N/A" end)% |"
')

## Token Usage

$(echo "$STATS" | jq -r '
"- Input Tokens: \(.totalInputTokens // 0 | . / 1000 | floor)K
- Output Tokens: \(.totalOutputTokens // 0 | . / 1000 | floor)K
- Total Tokens: \(((.totalInputTokens // 0) + (.totalOutputTokens // 0)) / 1000 | floor)K"
')

## Complexity Distribution

$(echo "$STATS" | jq -r '
"| Complexity | Stories |
|------------|---------|
| Simple | \(.complexityBreakdown.simple // 0) |
| Medium | \(.complexityBreakdown.medium // 0) |
| Complex | \(.complexityBreakdown.complex // 0) |
| Expert | \(.complexityBreakdown.expert // 0) |"
')

## Escalation Rate

$(echo "$STATS" | jq -r '
"- Total Escalations: \(.escalations // 0)/\(.totalStories // 0) stories (\(if (.totalStories // 0) > 0 then ((.escalations // 0) / .totalStories * 100) | floor else 0 end)%)"
')

## Model Usage

$(echo "$STATS" | jq -r '
.modelUsage // [] | if length > 0 then
  "| Model | Stories |\n|-------|---------|" + "\n" + (map("| \(.model // "unknown") | \(.count) |") | join("\n"))
else
  "No model usage data available"
end
')

---

*Generated by Relentless Learning System*
EOF
